--
-- PostgreSQL database dump
--

\restrict Ssn3nVrUEVLpJfK90OyWPw0wWxhupbJQYjHuPPr5BgC4JcMHvU01O8H39hg7XLz

-- Dumped from database version 16.13
-- Dumped by pg_dump version 18.2

-- Started on 2026-04-15 01:26:20

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 226 (class 1259 OID 16479)
-- Name: car; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.car (
    id_car integer NOT NULL,
    id_status integer NOT NULL,
    id_rate integer NOT NULL,
    stamp character varying(100) NOT NULL,
    model character varying(100) NOT NULL,
    year_of_release smallint NOT NULL,
    colour character varying(100) NOT NULL,
    mileage numeric NOT NULL,
    state_number character varying(50) NOT NULL
);


ALTER TABLE public.car OWNER TO postgres;

--
-- TOC entry 236 (class 1259 OID 16601)
-- Name: car_id_car_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.car ALTER COLUMN id_car ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.car_id_car_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 16453)
-- Name: client; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.client (
    id_client integer NOT NULL,
    id_drivers_license integer NOT NULL,
    id_passport integer NOT NULL,
    id_client_authorization integer NOT NULL,
    surname character varying(100) NOT NULL,
    name character varying(100) NOT NULL,
    patronymic character varying(100) NOT NULL,
    phone_number text NOT NULL,
    address character varying(100) NOT NULL,
    email character varying(100) NOT NULL
);


ALTER TABLE public.client OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 16474)
-- Name: client_authorization; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.client_authorization (
    "id_client authorization" integer NOT NULL,
    login character varying(100) NOT NULL,
    password character varying(100) NOT NULL
);


ALTER TABLE public.client_authorization OWNER TO postgres;

--
-- TOC entry 237 (class 1259 OID 16602)
-- Name: client_authorization_id_client authorization_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.client_authorization ALTER COLUMN "id_client authorization" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."client_authorization_id_client authorization_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 240 (class 1259 OID 16619)
-- Name: client_id_client_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.client ALTER COLUMN id_client ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.client_id_client_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 215 (class 1259 OID 16399)
-- Name: contract; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.contract (
    id_contract integer NOT NULL,
    id_client integer NOT NULL,
    id_employee integer NOT NULL,
    id_car integer NOT NULL,
    id_starus_of_the_agreement integer NOT NULL,
    id_discounts integer,
    id_penalties integer,
    "rental amount" numeric NOT NULL,
    "start date" date NOT NULL,
    "end date" date NOT NULL,
    "total amount" numeric NOT NULL
);


ALTER TABLE public.contract OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16433)
-- Name: contract-payment; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."contract-payment" (
    "id_contract-payment" integer NOT NULL,
    id_contract integer NOT NULL,
    id_payment integer NOT NULL
);


ALTER TABLE public."contract-payment" OWNER TO postgres;

--
-- TOC entry 244 (class 1259 OID 16635)
-- Name: contract-payment_id_contract-payment_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."contract-payment" ALTER COLUMN "id_contract-payment" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."contract-payment_id_contract-payment_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 243 (class 1259 OID 16626)
-- Name: contract_id_contract_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.contract ALTER COLUMN id_contract ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contract_id_contract_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 218 (class 1259 OID 16416)
-- Name: discounts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.discounts (
    id_discounts integer NOT NULL,
    title character varying(100) NOT NULL,
    " percent(%)" numeric(100,0) NOT NULL
);


ALTER TABLE public.discounts OWNER TO postgres;

--
-- TOC entry 242 (class 1259 OID 16621)
-- Name: discounts_id_discounts_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.discounts ALTER COLUMN id_discounts ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.discounts_id_discounts_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 16460)
-- Name: drivers_license; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.drivers_license (
    id_drivers_license integer NOT NULL,
    category character varying(100) NOT NULL,
    date_of_issue date NOT NULL,
    validity_period date NOT NULL,
    number character varying(100) NOT NULL
);


ALTER TABLE public.drivers_license OWNER TO postgres;

--
-- TOC entry 239 (class 1259 OID 16610)
-- Name: driver's_license_id_driver's_license_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.drivers_license ALTER COLUMN id_drivers_license ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."driver's_license_id_driver's_license_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 16467)
-- Name: passport; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.passport (
    id_passport integer NOT NULL,
    series numeric NOT NULL,
    number numeric NOT NULL,
    issued_by_whom character varying(200) NOT NULL,
    when_issued character varying(100) NOT NULL
);


ALTER TABLE public.passport OWNER TO postgres;

--
-- TOC entry 238 (class 1259 OID 16603)
-- Name: passport_id_passport_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.passport ALTER COLUMN id_passport ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.passport_id_passport_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 16438)
-- Name: payment; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.payment (
    id_payment integer NOT NULL,
    id_payment_method integer NOT NULL,
    id_type integer NOT NULL,
    payment_date date NOT NULL,
    amount numeric NOT NULL
);


ALTER TABLE public.payment OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 16443)
-- Name: payment_method; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.payment_method (
    "id_ payment method" integer NOT NULL,
    title character varying(100) NOT NULL
);


ALTER TABLE public.payment_method OWNER TO postgres;

--
-- TOC entry 234 (class 1259 OID 16596)
-- Name: payment method_id_ payment method_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.payment_method ALTER COLUMN "id_ payment method" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."payment method_id_ payment method_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 235 (class 1259 OID 16597)
-- Name: payment_id_payment_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.payment ALTER COLUMN id_payment ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payment_id_payment_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 217 (class 1259 OID 16411)
-- Name: penalties; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.penalties (
    id_penalties integer NOT NULL,
    title character varying(100) NOT NULL,
    "summ " numeric NOT NULL
);


ALTER TABLE public.penalties OWNER TO postgres;

--
-- TOC entry 241 (class 1259 OID 16620)
-- Name: penalties_id_penalties_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.penalties ALTER COLUMN id_penalties ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.penalties_id_penalties_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 16491)
-- Name: rate; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.rate (
    id_rate integer NOT NULL,
    title character varying(100) NOT NULL,
    price numeric NOT NULL
);


ALTER TABLE public.rate OWNER TO postgres;

--
-- TOC entry 233 (class 1259 OID 16595)
-- Name: rate_id_rate_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.rate ALTER COLUMN id_rate ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rate_id_rate_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 216 (class 1259 OID 16406)
-- Name: starus_of_the_agreement; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.starus_of_the_agreement (
    id_starus_of_the_agreement integer NOT NULL,
    title character varying(100) NOT NULL
);


ALTER TABLE public.starus_of_the_agreement OWNER TO postgres;

--
-- TOC entry 232 (class 1259 OID 16594)
-- Name: starus_of_the_agreement_id_starus_of_the_agreement_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.starus_of_the_agreement ALTER COLUMN id_starus_of_the_agreement ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.starus_of_the_agreement_id_starus_of_the_agreement_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 227 (class 1259 OID 16486)
-- Name: status; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.status (
    id_status integer NOT NULL,
    title character varying(100) NOT NULL
);


ALTER TABLE public.status OWNER TO postgres;

--
-- TOC entry 231 (class 1259 OID 16593)
-- Name: status_id_status_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.status ALTER COLUMN id_status ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.status_id_status_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 229 (class 1259 OID 16582)
-- Name: type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.type (
    id_tipe integer NOT NULL,
    title character varying(100) NOT NULL
);


ALTER TABLE public.type OWNER TO postgres;

--
-- TOC entry 230 (class 1259 OID 16592)
-- Name: type_id_tipe_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.type ALTER COLUMN id_tipe ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.type_id_tipe_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 5003 (class 0 OID 16479)
-- Dependencies: 226
-- Data for Name: car; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.car (id_car, id_status, id_rate, stamp, model, year_of_release, colour, mileage, state_number) FROM stdin;
3	2	9	Suzuki	Jimny	2015	Зелёный	120000	А783КК76
4	2	5	Audi	A6	2020	Чёрный	40000	E900РК76
5	4	3	Toyota	Corolla	2015	Серый	12000	Р457ВК76
6	2	7	BMW	M4	2021	Чёрный	400000	E978РК76
2	1	7	Audi	R8	2015	Белый	40000	K102AK76
1	1	3	Lada	Vesta	2010	Белый	54000	A456KE76
\.


--
-- TOC entry 4999 (class 0 OID 16453)
-- Dependencies: 222
-- Data for Name: client; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.client (id_client, id_drivers_license, id_passport, id_client_authorization, surname, name, patronymic, phone_number, address, email) FROM stdin;
1	1	1	1	Иванов	Сергей	Александрович	+7(985)123-45-67	г. Ярославль, ул. Свободы, д. 12, кв. 45	sergey.ivanov85@yandex.ru
2	2	2	2	Петрова	Анна	Викторовна	+7(902)456-78-90	г. Ярославль, ул. Чехова, д. 23, кв. 89	anna.petрова92@mail.ru
3	3	3	3	Смирнов	Дмитрий	Олегович	+7 (978) 321-09-87	г. Ярославль, пр-т Толбухина, д. 34, кв. 67	dmitry.smirnov77@gmail.com
4	4	4	4	Кузнецова	Ольга	Сергеевна	+7 (910) 654-32-10	г. Ярославль, ул. Гагарина, д. 56, кв. 14	olga.kuznecova09@outlook.com
5	5	5	5	Сидоров	 Михаил	Петрович	 +7 (903) 789-01-23	г. Ярославль, ул. Угличская, д. 78, кв. 23	mikhail.sidorov88@yandex.ru
6	6	6	6	Морозова	Екатерина	Игоревна	+7 (960) 234-56-78	 г. Ярославль, ул. Фрунзе, д. 41, кв. 76	ekaterina.morozova95@mail.ru
\.


--
-- TOC entry 5002 (class 0 OID 16474)
-- Dependencies: 225
-- Data for Name: client_authorization; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.client_authorization ("id_client authorization", login, password) FROM stdin;
1	pg_client	TestPass123!
2	yaroslav_test	Yaroslavl2026#
3	client_demo	SecurePass77@
4	testuser1	DBadmin2026!
5	postgres_test	Yarl2026Secure$
6	user_yar	ClientPass456!
7	hjyjkykhn	Yarl2026Secure$
8	tyujyukyu	using System;
9	укееа	цук23
10	укееа1	цук231
11	ertyu	rty45
\.


--
-- TOC entry 4992 (class 0 OID 16399)
-- Dependencies: 215
-- Data for Name: contract; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.contract (id_contract, id_client, id_employee, id_car, id_starus_of_the_agreement, id_discounts, id_penalties, "rental amount", "start date", "end date", "total amount") FROM stdin;
2	2	1	4	1	1	\N	50000	2025-07-25	2025-08-15	40000
3	3	3	6	1	8	1	12000	2025-08-15	2025-08-23	11300
4	1	1	1	3	\N	\N	3500	2026-04-14	2026-04-15	3500
5	1	1	1	3	\N	\N	3500	2026-04-14	2026-04-16	7000
1	1	2	3	1	\N	1	3500	2025-06-01	2025-06-05	4000
\.


--
-- TOC entry 4996 (class 0 OID 16433)
-- Dependencies: 219
-- Data for Name: contract-payment; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."contract-payment" ("id_contract-payment", id_contract, id_payment) FROM stdin;
1	1	2
2	2	3
3	3	5
4	1	9
\.


--
-- TOC entry 4995 (class 0 OID 16416)
-- Dependencies: 218
-- Data for Name: discounts; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.discounts (id_discounts, title, " percent(%)") FROM stdin;
1	первый заказ	20
2	за 10 дней аренды	5
3	за 30 дней аренды	15
4	после 50+ дней или суммы от 150 000 ₽	20
5	стаж больше 10 лет	25
6	инвалидность	20
7	корпоративная	15
8	день рождение	10
\.


--
-- TOC entry 5000 (class 0 OID 16460)
-- Dependencies: 223
-- Data for Name: drivers_license; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.drivers_license (id_drivers_license, category, date_of_issue, validity_period, number) FROM stdin;
1	AB	2020-05-15	2030-05-15	12AB 567890
2	AB	2021-11-28	2031-11-28	34CD 123456
3	ABC	2023-07-03	2033-07-03	56EF 789012
4	B	2025-02-20	2035-02-20	78GH 345678
5	ABC	2022-08-10	2032-08-10	90IJ 901234
6	AB	2020-09-27	2030-09-27	23KL 456789
\.


--
-- TOC entry 5001 (class 0 OID 16467)
-- Dependencies: 224
-- Data for Name: passport; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.passport (id_passport, series, number, issued_by_whom, when_issued) FROM stdin;
1	4509	123456	ОТДЕЛЕНИЕ УФМС РОССИИ ПО ЯРОСЛАВСКОЙ ОБЛАСТИ ПО ЛЕНИНСКОМУ РАЙОНУ	15.03.2018
2	5512	789012	УВД ПО КИРОВскому РАЙОНУ Г. ЯРОСЛАВЛЯ УМВД РОССИИ ПО ЯРОСЛАВСКОЙ ОБЛАСТИ	22.07.2020
3	4608	345678	ОТДЕЛ УФМС РОССИИ ПО ДЫАТЛОВскому РАЙОНУ В Г. ЯРОСЛАВЛЕ	10.11.2022
4	5524	901234	МФ ОУФМС РОССИИ ПО ЗАВОЛЖСКОМУ РАЙОНУ Г. ЯРОСЛАВЛЯ	05.05.2024
5	4511	567890	ОТДЕЛ УФМС РОССИИ ПО КИРОВСКОМУ РАЙОНУ Г. ЯРОСЛАВЛЯ	18.09.2019
6	5509	234567	УМВД РОССИИ ПО ЗАВОЛЖСКОМУ РАЙОНУ ЯРОСЛАВСКОЙ ОБЛАСТИ	30.01.2021
\.


--
-- TOC entry 4997 (class 0 OID 16438)
-- Dependencies: 220
-- Data for Name: payment; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.payment (id_payment, id_payment_method, id_type, payment_date, amount) FROM stdin;
1	3	3	2025-02-15	500
2	2	1	2025-04-30	1500
3	1	1	2025-06-15	500
4	1	2	2025-06-24	1500
5	1	3	2025-06-26	1000
6	4	2	2025-07-01	1000
7	2	2	2025-07-03	500
8	4	1	2025-07-10	500
9	3	3	2025-08-14	500
\.


--
-- TOC entry 4998 (class 0 OID 16443)
-- Dependencies: 221
-- Data for Name: payment_method; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.payment_method ("id_ payment method", title) FROM stdin;
1	банковская карта
2	наличка
3	онлайн
4	QR-код
\.


--
-- TOC entry 4994 (class 0 OID 16411)
-- Dependencies: 217
-- Data for Name: penalties; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.penalties (id_penalties, title, "summ ") FROM stdin;
1	Превышение скорости (20–40 км/ч)	500.00
2	Превышение (40–60 км/ч)	1500.00
3	Превышение (60–80 км/ч)	2500.00
4	Парковка на газоне	5000.00
5	Потеря аптечки	4000.00
6	Передача руля неуказанному водителю	50000.00
7	Выезд за зону	10000.00
8	Просрочка возврата	4000.00
\.


--
-- TOC entry 5005 (class 0 OID 16491)
-- Dependencies: 228
-- Data for Name: rate; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.rate (id_rate, title, price) FROM stdin;
1	A-класс	2000
2	B-класс	3000
3	C-класс	3500
4	D-класс	4500
5	E-класс	6000
6	F-класс	7000
7	S-класс	8000
8	M-класс	10000
9	J-класс	6000
\.


--
-- TOC entry 4993 (class 0 OID 16406)
-- Dependencies: 216
-- Data for Name: starus_of_the_agreement; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.starus_of_the_agreement (id_starus_of_the_agreement, title) FROM stdin;
1	Активен
2	Завершен
3	Отменен
\.


--
-- TOC entry 5004 (class 0 OID 16486)
-- Dependencies: 227
-- Data for Name: status; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.status (id_status, title) FROM stdin;
1	свободен
2	в аренде
3	на ТО
4	продан
5	В аренде
\.


--
-- TOC entry 5006 (class 0 OID 16582)
-- Dependencies: 229
-- Data for Name: type; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.type (id_tipe, title) FROM stdin;
1	предоплата
2	доплата
3	штраф
\.


--
-- TOC entry 5027 (class 0 OID 0)
-- Dependencies: 236
-- Name: car_id_car_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.car_id_car_seq', 6, true);


--
-- TOC entry 5028 (class 0 OID 0)
-- Dependencies: 237
-- Name: client_authorization_id_client authorization_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."client_authorization_id_client authorization_seq"', 11, true);


--
-- TOC entry 5029 (class 0 OID 0)
-- Dependencies: 240
-- Name: client_id_client_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.client_id_client_seq', 6, true);


--
-- TOC entry 5030 (class 0 OID 0)
-- Dependencies: 244
-- Name: contract-payment_id_contract-payment_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."contract-payment_id_contract-payment_seq"', 4, true);


--
-- TOC entry 5031 (class 0 OID 0)
-- Dependencies: 243
-- Name: contract_id_contract_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.contract_id_contract_seq', 5, true);


--
-- TOC entry 5032 (class 0 OID 0)
-- Dependencies: 242
-- Name: discounts_id_discounts_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.discounts_id_discounts_seq', 8, true);


--
-- TOC entry 5033 (class 0 OID 0)
-- Dependencies: 239
-- Name: driver's_license_id_driver's_license_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."driver''s_license_id_driver''s_license_seq"', 12, true);


--
-- TOC entry 5034 (class 0 OID 0)
-- Dependencies: 238
-- Name: passport_id_passport_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.passport_id_passport_seq', 6, true);


--
-- TOC entry 5035 (class 0 OID 0)
-- Dependencies: 234
-- Name: payment method_id_ payment method_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."payment method_id_ payment method_seq"', 4, true);


--
-- TOC entry 5036 (class 0 OID 0)
-- Dependencies: 235
-- Name: payment_id_payment_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.payment_id_payment_seq', 9, true);


--
-- TOC entry 5037 (class 0 OID 0)
-- Dependencies: 241
-- Name: penalties_id_penalties_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.penalties_id_penalties_seq', 8, true);


--
-- TOC entry 5038 (class 0 OID 0)
-- Dependencies: 233
-- Name: rate_id_rate_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.rate_id_rate_seq', 9, true);


--
-- TOC entry 5039 (class 0 OID 0)
-- Dependencies: 232
-- Name: starus_of_the_agreement_id_starus_of_the_agreement_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.starus_of_the_agreement_id_starus_of_the_agreement_seq', 14, true);


--
-- TOC entry 5040 (class 0 OID 0)
-- Dependencies: 231
-- Name: status_id_status_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.status_id_status_seq', 5, true);


--
-- TOC entry 5041 (class 0 OID 0)
-- Dependencies: 230
-- Name: type_id_tipe_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.type_id_tipe_seq', 3, true);


--
-- TOC entry 4828 (class 2606 OID 16485)
-- Name: car car_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.car
    ADD CONSTRAINT car_pkey PRIMARY KEY (id_car);


--
-- TOC entry 4826 (class 2606 OID 16478)
-- Name: client_authorization client authorization_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.client_authorization
    ADD CONSTRAINT "client authorization_pkey" PRIMARY KEY ("id_client authorization");


--
-- TOC entry 4820 (class 2606 OID 16459)
-- Name: client client_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.client
    ADD CONSTRAINT client_pkey PRIMARY KEY (id_client);


--
-- TOC entry 4814 (class 2606 OID 16437)
-- Name: contract-payment contract-payment_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."contract-payment"
    ADD CONSTRAINT "contract-payment_pkey" PRIMARY KEY ("id_contract-payment", id_payment);


--
-- TOC entry 4806 (class 2606 OID 16405)
-- Name: contract contract_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.contract
    ADD CONSTRAINT contract_pkey PRIMARY KEY (id_contract);


--
-- TOC entry 4812 (class 2606 OID 16420)
-- Name: discounts discounts_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.discounts
    ADD CONSTRAINT discounts_pkey PRIMARY KEY (id_discounts);


--
-- TOC entry 4822 (class 2606 OID 16466)
-- Name: drivers_license driver's license_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.drivers_license
    ADD CONSTRAINT "driver's license_pkey" PRIMARY KEY (id_drivers_license);


--
-- TOC entry 4824 (class 2606 OID 16473)
-- Name: passport passport_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.passport
    ADD CONSTRAINT passport_pkey PRIMARY KEY (id_passport);


--
-- TOC entry 4818 (class 2606 OID 16447)
-- Name: payment_method payment method_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.payment_method
    ADD CONSTRAINT "payment method_pkey" PRIMARY KEY ("id_ payment method");


--
-- TOC entry 4816 (class 2606 OID 16442)
-- Name: payment payment_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.payment
    ADD CONSTRAINT payment_pkey PRIMARY KEY (id_payment);


--
-- TOC entry 4810 (class 2606 OID 16415)
-- Name: penalties penalties_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.penalties
    ADD CONSTRAINT penalties_pkey PRIMARY KEY (id_penalties);


--
-- TOC entry 4832 (class 2606 OID 16495)
-- Name: rate rate_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rate
    ADD CONSTRAINT rate_pkey PRIMARY KEY (id_rate);


--
-- TOC entry 4808 (class 2606 OID 16410)
-- Name: starus_of_the_agreement starus_of_the_agreement_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.starus_of_the_agreement
    ADD CONSTRAINT starus_of_the_agreement_pkey PRIMARY KEY (id_starus_of_the_agreement);


--
-- TOC entry 4830 (class 2606 OID 16490)
-- Name: status status_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.status
    ADD CONSTRAINT status_pkey PRIMARY KEY (id_status);


--
-- TOC entry 4834 (class 2606 OID 16586)
-- Name: type type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.type
    ADD CONSTRAINT type_pkey PRIMARY KEY (id_tipe);


--
-- TOC entry 4835 (class 2606 OID 16511)
-- Name: contract id_car; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.contract
    ADD CONSTRAINT id_car FOREIGN KEY (id_car) REFERENCES public.car(id_car) NOT VALID;


--
-- TOC entry 4836 (class 2606 OID 16496)
-- Name: contract id_client; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.contract
    ADD CONSTRAINT id_client FOREIGN KEY (id_client) REFERENCES public.client(id_client) NOT VALID;


--
-- TOC entry 4844 (class 2606 OID 16541)
-- Name: client id_client authorization; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.client
    ADD CONSTRAINT "id_client authorization" FOREIGN KEY (id_client_authorization) REFERENCES public.client_authorization("id_client authorization") NOT VALID;


--
-- TOC entry 4840 (class 2606 OID 16561)
-- Name: contract-payment id_contract; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."contract-payment"
    ADD CONSTRAINT id_contract FOREIGN KEY (id_contract) REFERENCES public.contract(id_contract) NOT VALID;


--
-- TOC entry 4837 (class 2606 OID 16521)
-- Name: contract id_discounts; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.contract
    ADD CONSTRAINT id_discounts FOREIGN KEY (id_discounts) REFERENCES public.discounts(id_discounts) NOT VALID;


--
-- TOC entry 4845 (class 2606 OID 16652)
-- Name: client id_drivers_license; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.client
    ADD CONSTRAINT id_drivers_license FOREIGN KEY (id_drivers_license) REFERENCES public.drivers_license(id_drivers_license) NOT VALID;


--
-- TOC entry 4846 (class 2606 OID 16536)
-- Name: client id_passport; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.client
    ADD CONSTRAINT id_passport FOREIGN KEY (id_passport) REFERENCES public.passport(id_passport) NOT VALID;


--
-- TOC entry 4841 (class 2606 OID 16566)
-- Name: contract-payment id_payment; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."contract-payment"
    ADD CONSTRAINT id_payment FOREIGN KEY (id_payment) REFERENCES public.payment(id_payment) NOT VALID;


--
-- TOC entry 4842 (class 2606 OID 16571)
-- Name: payment id_payment method; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.payment
    ADD CONSTRAINT "id_payment method" FOREIGN KEY (id_payment_method) REFERENCES public.payment_method("id_ payment method") NOT VALID;


--
-- TOC entry 4838 (class 2606 OID 16526)
-- Name: contract id_penalties; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.contract
    ADD CONSTRAINT id_penalties FOREIGN KEY (id_penalties) REFERENCES public.penalties(id_penalties) NOT VALID;


--
-- TOC entry 4847 (class 2606 OID 16551)
-- Name: car id_rate; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.car
    ADD CONSTRAINT id_rate FOREIGN KEY (id_rate) REFERENCES public.rate(id_rate) NOT VALID;


--
-- TOC entry 4839 (class 2606 OID 16516)
-- Name: contract id_starus_of_the_agreement; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.contract
    ADD CONSTRAINT id_starus_of_the_agreement FOREIGN KEY (id_starus_of_the_agreement) REFERENCES public.starus_of_the_agreement(id_starus_of_the_agreement) NOT VALID;


--
-- TOC entry 4848 (class 2606 OID 16546)
-- Name: car id_status; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.car
    ADD CONSTRAINT id_status FOREIGN KEY (id_status) REFERENCES public.status(id_status) NOT VALID;


--
-- TOC entry 4843 (class 2606 OID 16587)
-- Name: payment id_type; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.payment
    ADD CONSTRAINT id_type FOREIGN KEY (id_type) REFERENCES public.type(id_tipe) NOT VALID;


-- Completed on 2026-04-15 01:26:21

--
-- PostgreSQL database dump complete
--

\unrestrict Ssn3nVrUEVLpJfK90OyWPw0wWxhupbJQYjHuPPr5BgC4JcMHvU01O8H39hg7XLz

